- hosts: localhost
  gather_facts: False
  tasks:
  - include: "{{ item }}.yaml"
    loop:
    - camel_to_snake
    - expand_vlans
    - flatten_list_of_dicts
    - keep_keys
    - rekey_on_members
    - nxos_flatten_table_row
    - replace_keys
    - set_root_key
    - stats
    - str_to_native
    - unnest
    - yaql
