- hosts: all
  gather_facts: false
  tasks:
  - include_role:
      name: nmake.jetpack.gather_states
    vars:
      nxos_engine: xml
      fact_key: before
      gather_state:
      - all
  - debug:
      msg: Make changes here
  - include_role:
      name: nmake.jetpack.gather_states
    vars:
      nxos_engine: xml
      fact_key: after
      gather_state:
      - all
  - name: Compare the before and after in dotted format
    nmake.jetpack.fact_diff:
      before: "{{ before|default({})|nmake.jetpack.to_dotted }}"
      after: "{{ after|default({})|nmake.jetpack.to_dotted }}"
