- hosts: all
  gather_facts: false
  vars:
    state_per_os: # these should really go in the inventory :)
      nxos:
        gather_states:
        - all
        - '!fex'
        - '!vlan.private_vlan'
        - '!vpc'
      eos:
        gather_states:
        - all
        - '!cdp'
        - '!fex'
        - '!hardware'
        - '!system'
        - '!vpc'
        - '!vlan.private_vlan'
      ios:
        gather_states:
        - all
        - '!fex'
        - '!hardware'
        - '!lldp'
        - '!mac'
        - '!spanning_tree'
        - '!system'
        - '!vlan'
        - '!vlan.private_vlan'
        - '!vpc'
      vyos:
        gather_states:
        - all

  roles:
  - role: nmake.jetpack.gather_states
    gather_states: "{{ state_per_os[ansible_network_os]['gather_states'] }}"
  tasks:
  - debug:
      var: ansible_facts
