- hosts: nxos101
  gather_facts: False
  tasks:
  - nmake.jetpack.cli_parse_transform:
      engine: native_json
      commands:
      - command: show interface Eth1/1-2
        set_fact: True
        transform:
        - name: nxos_flatten_table_row
          plural: True
        - name: rekey_on_members
          members:
          - interface
        - name: keep_keys
          keys:
          - admin_state
          - ^state$
        - name: to_dotted
        - name: set_root_key
          key: interfaces
  - set_fact:
      what_i_want:
        interfaces.Ethernet1/1.admin_state: up
        interfaces.Ethernet1/1.state: up
        interfaces.Ethernet1/2.admin_state: up
        interfaces.Ethernet1/2.state: up
  - nmake.jetpack.fact_diff:
      before: "{{ interfaces }}"
      after: "{{ what_i_want }}"
    register: everything_is_good
  - assert:
      that: not everything_is_good.changed
