- hosts: nxos101
  gather_facts: False
  tasks:
  - set_fact:
      desc_to_match: '^esx'
  - nmake.jetpack.cli_parse_transform:
      engine: native_json
      commands:
      - command: show interface
        set_fact: True
        transform:
        - name: nxos_flatten_table_row
          plural: True
        - name: keep_keys
          keys:
          - admin_state
          - ^state$
          - desc
          - interface
  - set_fact:
      down: "{{ interfaces|selectattr('desc', 'defined')
                |selectattr('desc', 'match', desc_to_match)
                |selectattr('state', 'equalto', 'down')
                | list }}"

  - assert:
      that: "{{ not down }}"
