---
- name: "nxos.arp: show ip arp vrf all"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show ip arp vrf all"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: arp
        - name: set_root_key
          key: "{{ fact_key }}"
