---
- name: "nxos.interfaces: show interface"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show interface"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
          plural: true
        - name: set_root_key
          key: interfaces
        - name: set_root_key
          key: "{{ fact_key }}"

- name: "nxos.interfaces: show interface counters errors"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
    - command: "show interface counters errors"
      set_fact: False
      transform:
      - name: "str_to_native"
      - name: "nxos_flatten_table_row"
      - name: set_root_key
        key: errors
      - name: set_root_key
        key: counters
      - name: set_root_key
        key: interface
      - name: set_root_key
        key: "{{ fact_key }}"

- name: "nxos.interfaces: show interface switchport"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
    - command: "show interface switchport"
      set_fact: False
      transform:
      - name: "nxos_flatten_table_row"
      - name: set_root_key
        key: switchport
      - name: set_root_key
        key: interface
      - name: set_root_key
        key: "{{ fact_key }}"

- name: "nxos.interfaces: show interface transceiver"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
    - command: "show interface transceiver"
      set_fact: False
      transform:
      - name: "nxos_flatten_table_row"
      - name: set_root_key
        key: transceiver
      - name: set_root_key
        key: interface
      - name: set_root_key
        key: "{{ fact_key }}"
