---
- name: "nxos.mlag: show vpc"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show vpc"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: vpc
        - name: set_root_key
          key: "{{ fact_key }}"

- name: "nxos.mlag: show vpc consistency-parameters global"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show vpc consistency-parameters global"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: global
        - name: set_root_key
          key: consistency_parameters
        - name: set_root_key
          key: vpc
        - name: set_root_key
          key: "{{ fact_key }}"

- name: "nxos.mlag: show vpc consistency-parameters vlans"
  nmake.jetpack.cli_parse_transform:
    engine: "native_json"
    commands:
      - command: "show vpc consistency-parameters vlans"
        set_fact: True
        transform:
        - name: "nxos_flatten_table_row"
        - name: set_root_key
          key: vlans
        - name: set_root_key
          key: consistency_parameters
        - name: set_root_key
          key: vpc
        - name: set_root_key
          key: "{{ fact_key }}"
