- set_fact:
    host_facts: "{{ hostvars.localhost.host_facts|default({})|
                    combine({inventory_hostname: ansible_facts}) }}"
    delegate_to: localhost
    delegate_facts: True


- name: Save the file
  template:
    src: object_browser_all.html.j2
    dest: "{{ directory|default(playbook_dir + '/reports') }}/{{ filename|default('all_hosts_' + current_date + '.html') }}"
  connection: local
  vars:
    rhostvars: "{{ hostvars }}"
    rkeypath: "{{ dotted_key_path|default(None) }}"
    rtitle: "{{ title|default('Object browser report for all hosts') }}"
    rplay_hosts: "{{ ansible_play_hosts_all }}"
    rdate: "{{ current_date }}"
    rsummary: "{{ summary|default('report summary') }}"
  delegate_to: localhost
  run_once: true
