
- name: Get a timestamp
  set_fact:
    current_date: "{{ lookup('pipe','date') }}"
  delegate_to: localhost
  run_once: True

- name: Creates reports directory
  file:
    path: "{{ report_dir|default(playbook_dir + '/reports') }}"
    state: directory
  run_once: True

- name: Save the file
  template:
    src: object_browser.html.j2
    dest: "{{ directory|default(playbook_dir + '/reports') }}/{{ filename|default(inventory_hostname + '_' + current_date + 'html') }}"
  connection: local
  vars:
    rdata: "{{ data|default({'hostvars': hostvars[inventory_hostname]}) }}"
    rtitle: "{{ title|default('Object browser report for ' + inventory_hostname) }}"
    rdate: "{{ current_date }}"
    rsummary: "{{ summary|default('report summary') }}"
