
- name: Get a timestamp
  set_fact:
    current_date: "{{ lookup('pipe','date') }}"
  delegate_to: localhost
  run_once: True

- name: Creates reports directory
  file:
    path: "{{ report_dir|default(playbook_dir + '/reports') }}"
    state: directory
  run_once: True

- name: Include the report type file generator
  include: "{{ item }}"
  with_first_found:
  - "{{ report_format }}.yaml"
  - unfound_report_format.yaml
