
- name: Get a timestamp
  set_fact:
    current_date_long: "{{ lookup('pipe','date') }}"
    current_date_ts: "{{ lookup('pipe', 'date +%Y%m%d%H%M%S') }}"
  delegate_to: localhost
  run_once: True

- name: Creates reports directory
  file:
    path: "{{ report_dir|default(playbook_dir + '/reports') }}"
    state: directory
  run_once: True

- name: Include the report type file generator
  include: "{{ item }}"
  with_first_found:
  - "includes/{{ report_format }}.yaml"
  - includes/unfound_report_format.yaml
