
- name: Save the file
  template:
    src: object_browser.html.j2
    dest: "{{ directory|default(playbook_dir + '/reports') }}/{{ filename|default(inventory_hostname + '_' + current_date + 'html') }}"
  connection: local
  vars:
    rhostvars: "{{ hostvars[inventory_hostname] }}"
    rkeypath: "{{ dotted_key_path|default(None) }}"
    rtitle: "{{ title|default('Object browser report for ' + inventory_hostname) }}"
    rplay_hosts: "{{ ansible_play_hosts_all }}"
    rdate: "{{ current_date }}"
    rsummary: "{{ summary|default('report summary') }}"
