- name: "ios.interfaces: show interface"
  nmake.jetpack.cli_parse_transform:
    engine: "pyats"
    network_os: iosxe
    commands:
      - command: "show interface"
        set_fact: True
        transform:
        - name: set_root_key
          key: interfaces
        - name: set_root_key
          key: "{{ fact_key }}"
