- hosts: ios
  gather_facts: False
  collections:
  - nmake.jetpack
  vars:
    interfaces:
    - name: GigabitEthernet0/2
      description: 'Configured and Merged by Ansible Network'
      enabled: True
      metadata:
        int_type: host port
        last_changed: 9/3/2020
        changed_by: Brad Thornton
    - name: GigabitEthernet0/3
      description: connection to rhv12345
      metadata:
        int_type: rhv uplink
        last_changed: 9/3/2020
        changed_by: Brad Thornton
  tasks:
  - ready_for_modules:
      modules:
      - name: ios_interfaces
        data:
          config: "{{ interfaces }}"
    register: result
  - debug:
      var: result
