- hosts: all
  gather_facts: false
  tasks:
  - include_role:
      role: nmake.jetpack.object_browser
    vars:
      dotted_key_paths:
      - ansible_inventory_sources
      - ansible_version.full
      - groups
