- hosts: all
  gather_facts: false
  tasks:
  - nxos_config:
      lines:
      - description "management interface {{ 100 | random }}"
      parents: interface mgmt0
  - include_role:
      role: nmake.jetpack.object_browser
    vars:
      dotted_key_paths:
      - network_change_log.commands
      - network_change_log.summary
      directory: ./reports
      filename: "change_log.html"
      title: "Change log for all hosts"
      summary: "Change made to device using Ansible playbook"
      report_format: all_in_one
