- hosts: nxos101
  gather_facts: false
  vars:
    state_per_os: # these should really go in the inventory :)
      nxos:
        gather_states:
        - all
        - '!fex'
        - '!vlan.private_vlan'
        - '!vpc'
  roles:
  - role: nmake.jetpack.gather_states
    gather_states: "{{ state_per_os[ansible_network_os]['gather_states'] }}"
  - role: nmake.jetpack.object_browser
    dotted_key_paths:
    - gathered_states
    filename: "{{ inventory_hostname }}_gathered_states.html"

- hosts: nxos101
  gather_facts: false
  roles:
  - role: nmake.jetpack.gather_states
    only_stats: True
    fact_key: stats_info
    gather_states:
    - all
    - '!vpc'
  - role: nmake.jetpack.object_browser
    dotted_key_paths:
    - stats_info
    filename: "{{ inventory_hostname }}_gathered_states_stats_only.html"
